// Authentic Curated Real Instagram Reels Catalog
// Verified public Instagram reels across popular Indian & global creators

export const extractInstagramShortcode = (input) => {
  if (!input || typeof input !== "string") return "";
  const match = input.match(/(?:reel|reels|p)\/([A-Za-z0-9_-]+)/i);
  if (match) return match[1];
  const cleaned = input.trim().replace(/^@/, "");
  if (/^[A-Za-z0-9_-]{8,15}$/.test(cleaned)) return cleaned;
  return "";
};

export const INSTAGRAM_REELS_CATALOG = [
  {
    _id: "ig-virat-1",
    shortcode: "Dd_qYUyhZDF",
    creatorName: "virat.kohli",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=ViratKohli",
    videoUrl: "https://www.instagram.com/reel/Dd_qYUyhZDF/",
    caption: "Focused, relentless and pushing every single day 💪🏏 #viratkohli #training #cricket #discipline",
    musicTitle: "Original Audio • virat.kohli 👑",
    category: "cricket",
    likesCount: 1420000,
    sharesCount: 82000,
    commentsCount: 24500,
  },
  {
    _id: "ig-shraddha-1",
    shortcode: "C-U1J5qPZ8B",
    creatorName: "shraddhakapoor",
    creatorAvatar: "https://api.dicebear.com/10.x/lorelei/svg?seed=Shraddha",
    videoUrl: "https://www.instagram.com/reel/C-U1J5qPZ8B/",
    caption: "Chalo masti shuru karte hain! 💖✨ Aap sab ready ho? #shraddhakapoor #reels #trending",
    musicTitle: "Trending Reel Sound • Instagram ✨",
    category: "trending",
    likesCount: 980000,
    sharesCount: 44000,
    commentsCount: 18200,
  },
  {
    _id: "ig-dhoni-1",
    shortcode: "C5b6P-hI_p3",
    creatorName: "chennaiipl",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=CSKThala",
    videoUrl: "https://www.instagram.com/reel/C5b6P-hI_p3/",
    caption: "Thala entry madness! The decibel levels at Chepauk Stadium 🦁💛 #dhoni #thala #csk #ipl",
    musicTitle: "Whistle Podu Anthem • CSK 🦁",
    category: "cricket",
    likesCount: 2200000,
    sharesCount: 188000,
    commentsCount: 42000,
  },
  {
    _id: "ig-arijit-1",
    shortcode: "CGm_n80h72y",
    creatorName: "arijitsingh",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=ArijitSingh",
    videoUrl: "https://www.instagram.com/reel/CGm_n80h72y/",
    caption: "Raw acoustic unplugged piano vibes 🎹❤️ A feeling of peaceful nostalgia. #arijitsingh #soulful #music",
    musicTitle: "Acoustic Piano Session • Arijit Singh 🎵",
    category: "music",
    likesCount: 1850000,
    sharesCount: 91000,
    commentsCount: 29000,
  },
  {
    _id: "ig-carry-1",
    shortcode: "C7v78R-t6vX",
    creatorName: "carryminati",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=CarryMinati",
    videoUrl: "https://www.instagram.com/reel/C7v78R-t6vX/",
    caption: "Toh kaise hain aap log? 😂🔥 Har ek baat pe itna drama! #carryminati #comedy #funny #desi",
    musicTitle: "Carry Comedy Audio • CarryMinati 😂",
    category: "comedy",
    likesCount: 3100000,
    sharesCount: 210000,
    commentsCount: 52000,
  },
  {
    _id: "ig-techburner-1",
    shortcode: "DA5q8s1N-xS",
    creatorName: "techburner",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=TechBurner",
    videoUrl: "https://www.instagram.com/reel/DA5q8s1N-xS/",
    caption: "Yeh crazy gadget dekh ke hosh ud jayenge! 📱🚀 Extreme testing with full energy! #techburner #gadgets #tech",
    musicTitle: "Tech Burner BGM • Shlok Srivastava ⚡",
    category: "tech",
    likesCount: 1750000,
    sharesCount: 67000,
    commentsCount: 19400,
  },
  {
    _id: "ig-tseries-1",
    shortcode: "DAr0-4_P7iJ",
    creatorName: "tseries.official",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=TSeries",
    videoUrl: "https://www.instagram.com/reel/DAr0-4_P7iJ/",
    caption: "Latest Bollywood banger on loop across India! 🎶🕺 Tag your dance partner. #tseries #bollywooddance #viral",
    musicTitle: "Bollywood Trending Beats • T-Series 🎶",
    category: "trending",
    likesCount: 1400000,
    sharesCount: 82000,
    commentsCount: 14500,
  },
  {
    _id: "ig-bcci-1",
    shortcode: "C6E76-XN44H",
    creatorName: "indiancricketteam",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=TeamIndia",
    videoUrl: "https://www.instagram.com/reel/C6E76-XN44H/",
    caption: "Rohit Sharma & the boys celebrate in style 🇮🇳🏆 Pure emotion for a billion fans! #teamindia #bcci #cricket",
    musicTitle: "Lehra Do Anthem • Team India 🇮🇳",
    category: "cricket",
    likesCount: 4200000,
    sharesCount: 380000,
    commentsCount: 68000,
  },
  {
    _id: "ig-arijit-2",
    shortcode: "Cp1W4YlD0uU",
    creatorName: "arijitsingh",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=ArijitSingh",
    videoUrl: "https://www.instagram.com/reel/Cp1W4YlD0uU/",
    caption: "Thank you for singing your hearts out! 50,000 voices under one sky ✨🎤 #arijitsinghlive #concert #magic",
    musicTitle: "Live Concert Chorus • Arijit Singh 🌟",
    category: "music",
    likesCount: 1600000,
    sharesCount: 74000,
    commentsCount: 22000,
  },
  {
    _id: "ig-ashish-1",
    shortcode: "C85_x_eI93J",
    creatorName: "ashishchanchlani",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=AshishChanchlani",
    videoUrl: "https://www.instagram.com/reel/C85_x_eI93J/",
    caption: "Shaadi me rishtedaaron ke questions are unbearable 😂🤦‍♂️ Kisko relate hua? #ashishchanchlani #comedy #relatable",
    musicTitle: "ACV Funny Sound • Ashish Chanchlani 🤣",
    category: "comedy",
    likesCount: 2900000,
    sharesCount: 145000,
    commentsCount: 39000,
  },
  {
    _id: "ig-tech-1",
    shortcode: "DA-rP0-v9eB",
    creatorName: "tech_insider",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=TechInsider",
    videoUrl: "https://www.instagram.com/reel/DA-rP0-v9eB/",
    caption: "Mind-blowing AI and humanoid robotics tech breakthrough in 2026! 🤖💡 #future #technology #ai #robots",
    musicTitle: "Cyberpunk Future Synth • Tech Audio ⚡",
    category: "tech",
    likesCount: 1100000,
    sharesCount: 58000,
    commentsCount: 15000,
  },
  {
    _id: "ig-dance-1",
    shortcode: "DBa1u-P8z5Y",
    creatorName: "teamnaach",
    creatorAvatar: "https://api.dicebear.com/10.x/lorelei/svg?seed=TeamNaach",
    videoUrl: "https://www.instagram.com/reel/DBa1u-P8z5Y/",
    caption: "Desi Dhol and Bollywood energetic steps! Full energy wedding vibe 🔥💃 #teamnaach #dancechoreography #sangeet",
    musicTitle: "Dhol Beats & Bollywood Mashup • Team Naach 🥁",
    category: "trending",
    likesCount: 1350000,
    sharesCount: 66000,
    commentsCount: 18000,
  },
  {
    _id: "ig-rcb-1",
    shortcode: "DA-R9J4JvH6",
    creatorName: "royalchallengersbangalore",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=RCBKing",
    videoUrl: "https://www.instagram.com/reel/DA-R9J4JvH6/",
    caption: "Pure poetry in motion! King Kohli's iconic cover drive in slow motion 👑🏏 #rcb #viratkohli #chinnaswamy #cricket",
    musicTitle: "Play Bold Anthem • RCB 🔴⚫",
    category: "cricket",
    likesCount: 3800000,
    sharesCount: 240000,
    commentsCount: 49000,
  },
  {
    _id: "ig-music-3",
    shortcode: "C-k7v1vN8Lp",
    creatorName: "bollywood_vibes",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=BollyVibes",
    videoUrl: "https://www.instagram.com/reel/C-k7v1vN8Lp/",
    caption: "Heart touching Bollywood melody that hits right in the feels 🌧️🎶 #arijitsingh #romanticsongs #bollywood",
    musicTitle: "Bollywood Acoustic Melodies 🎵",
    category: "music",
    likesCount: 1250000,
    sharesCount: 63000,
    commentsCount: 16000,
  },
  {
    _id: "ig-tech-2",
    shortcode: "C-k3_h-v2oG",
    creatorName: "gadget_review_in",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=GadgetReview",
    videoUrl: "https://www.instagram.com/reel/C-k3_h-v2oG/",
    caption: "100X Moon zoom camera test in real-time! Mind-boggling clarity 📱🌕 #techreview #camera #zoom",
    musicTitle: "Flagship Gadget Unboxing Sound 📱",
    category: "tech",
    likesCount: 1450000,
    sharesCount: 72000,
    commentsCount: 21000,
  },
  {
    _id: "ig-comedy-2",
    shortcode: "C-fWzJ8R3dK",
    creatorName: "unwind_vibes",
    creatorAvatar: "https://api.dicebear.com/10.x/personas/svg?seed=UnwindVibes",
    videoUrl: "https://www.instagram.com/reel/C-fWzJ8R3dK/",
    caption: "Nostalgic 2000s Bollywood vibes that make you smile instantly! 🌸✨ #nostalgia #bollywood #90skids",
    musicTitle: "Retro Nostalgia Mix • Bollywood 🌸",
    category: "trending",
    likesCount: 1650000,
    sharesCount: 89000,
    commentsCount: 26000,
  },
];
